[tool.black]
line-length = 119
exclude = "migrations"

[tool.isort]
profile = "black"
line_length = 119
combine_as_imports = "True"
known_django = "django"
known_requests = "requests"
sections = "FUTURE,STDLIB,REQUESTS,DJANGO,THIRDPARTY,FIRSTPARTY,LOCALFOLDER"
