# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-23 17:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("whpf", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="result",
            name="limit_teams",
        ),
        migrations.RemoveField(
            model_name="result",
            name="rounds",
        ),
        migrations.RemoveField(
            model_name="result",
            name="show_player_name",
        ),
        migrations.RemoveField(
            model_name="result",
            name="shuffle_teams",
        ),
        migrations.RemoveField(
            model_name="result",
            name="time",
        ),
    ]
