# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-15 16:09
from __future__ import unicode_literals

import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whpf', '0004_auto_20160425_1804'),
    ]

    operations = [
        migrations.CreateModel(
            name='Options',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_roster_update', models.DateTimeField()),
            ],
        ),
        migrations.AlterModelManagers(
            name='player',
            managers=[
                ('all_players', django.db.models.manager.Manager()),
            ],
        ),
    ]
