# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-10-25 13:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("whpf", "0005_auto_20160615_1609"),
    ]

    operations = [
        migrations.AddField(
            model_name="player",
            name="being_updated",
            field=models.BooleanField(default=False),
        ),
    ]
