# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-01-25 21:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("whpf", "0008_team_times_guessed"),
    ]

    operations = [
        migrations.AddField(
            model_name="player",
            name="times_guessed_pct",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="team",
            name="times_guessed_pct",
            field=models.IntegerField(default=0),
        ),
    ]
