# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-02-17 18:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("whpf", "0010_play_playsetting"),
    ]

    operations = [
        migrations.AddField(
            model_name="play",
            name="legacy",
            field=models.BooleanField(default=False),
        ),
    ]
