# Generated by Django 2.2.2 on 2019-06-30 22:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whpf', '0011_play_legacy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='play',
            name='player',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
