"""
Updated by Fepe to Django 2.2
Django settings for WhoHePlayFor project.

Generated by 'django-admin startproject' using Django 1.9.5.

For more information on this file, see
https://docs.djangoproject.com/en/1.9/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.9/ref/settings/
"""

import os
from django.urls import reverse_lazy
# HEROKU
# import dj_database_url

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'hi-there'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DEBUG', True) != 'False'

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'social_django',
    'whpf',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'whoheplayfor.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'social_django.context_processors.backends',
                'social_django.context_processors.login_redirect',
                'whpf.context_processors.last_roster_update',
            ],
        },
    },
]

WSGI_APPLICATION = 'whoheplayfor.wsgi.application'


# Database
DATABASES = {
    'default': {
        'ENGINE': os.environ.get(
            'POSTGRES_ENGINE', 'django.db.backends.sqlite3',
        ),
        'NAME': os.environ.get(
            'POSTGRES_DB', os.path.join(BASE_DIR, 'db.sqlite3')
        ),
        'USER': os.environ.get('POSTGRES_USER', None),
        'HOST': os.environ.get('POSTGRES_HOST', None),
        'PASSWORD': os.environ.get('POSTGRES_PASSWORD', None)
    }
}

# HEROKU
# DATABASES['default'] = dj_database_url.config()


AUTHENTICATION_BACKENDS = [
    'social_core.backends.facebook.FacebookOAuth2',
    'social_core.backends.google.GoogleOAuth2',
    'social_core.backends.twitter.TwitterOAuth',
    'social_core.backends.reddit.RedditOAuth2',
    'django.contrib.auth.backends.ModelBackend',
]


# Password validation
AUTH_PASSWORD_VALIDATORS = []


# Internationalization
LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'US/Eastern'

USE_I18N = True

USE_L10N = True

USE_TZ = True

# Heroku
PROJECT_ROOT = os.path.dirname(os.path.abspath(__file__))

# Static files (CSS, JavaScript, Images)
STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(PROJECT_ROOT, 'staticfiles')


# LOGIN_URL = reverse_lazy("login")
LOGIN_URL = reverse_lazy("whpf:home")
LOGIN_REDIRECT_URL = reverse_lazy("whpf:home")
LOGOUT_REDIRECT_URL = reverse_lazy("whpf:home")


try:
    from .local_settings import *  # noqa: F401,F403
except ModuleNotFoundError:
    pass
