name: Django CI

on:
  push:
    branches: [master, uv]
  pull_request:
    branches: [master, uv]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 3

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5

      - name: Run Ruff
        uses: astral-sh/ruff-action@v2

      - name: Run tests and generate coverage report
        run: |
          docker compose -f docker-compose.ci.yml run backend /bin/bash -c "coverage run -m pytest && coverage report && coverage xml"

      - name: Upload Coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          fail_ci_if_error: true # optional (default = false)
          verbose: true # optional (default = false)
          token: ${{ secrets.CODECOV_TOKEN }} # required
